name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x'

    - name: Build
      working-directory: "./CodeLearningSpectaclesWPF"
      run: dotnet build -c Release

    - name: Publish
      working-directory: "./CodeLearningSpectaclesWPF"
      run: dotnet publish -c Release -o publish

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.0
        release_name: Release v1.0.0
        body: |
          Code learning wpf relrease.
        draft: false
        prerelease: false

    - name: Upload Executable
      uses: actions/upload-artifact@v2
      with:
        name: my-executable
        path: publish/*.exe
