name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x'

    - name: Build
      working-directory: "./CodeLearningSpectaclesWPF"
      run: dotnet build -c Release

    # Create a release
    - name: Create Release
      if: github.ref == 'refs/heads/main'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: v1.0.12
        release_name: Release v1.0.12
        draft: false
        prerelease: false

    # Upload asset to the release
    - name: Upload Release Asset
      if: github.ref == 'refs/heads/main'
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: CodeLearningSpectaclesWPF/CodeLearningSpectaclesWPF/bin/Release/net8.0-windows/CodeLearningSpectaclesWPF.exe
        asset_name: CodeLearningSpectaclesWPF.exe
        asset_content_type: application/octet-stream
