name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x'

    - name: Build
      working-directory: "./CodeLearningSpectaclesWPF"
      run: dotnet build -c Release

    - name: List Contents of Release Directory
      run: ls -R bin\Release\net8.0-windows

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: v1.0.4
        release_name: Release v1.0.4
        body: |
          Code learning wpf release.
        draft: false
        prerelease: false
        files: |
          bin/Release/net8.0-windows/**

    - name: Upload Executable
      uses: actions/upload-artifact@v2
      with:
        name: codelearningwpf
        path: bin\Release\net8.0-windows\*.{exe,dll}

